services:
  leggo:
    build: ./interface/
    container_name: leggo
    environment:
      - ENABLE_CRON=true
    depends_on:
      - mysql
      - redis
    volumes:
      - ../_data/logs/:/var/log/
      - ../_data/upload/:/var/www/leggo/site/public_html/assets/upload/
      - ../_data/upload/:/var/www/leggo/manager/public_html/assets/upload/
      - ../site/public_html/:/var/www/leggo/site/public_html/
      - ../site/app/:/var/www/leggo/site/app/
      - ../site/cgi-bin/:/var/www/leggo/site/cgi-bin/
      - ../site/tests/:/var/www/leggo/site/tests/
      - ../site/phpunit.xml:/var/www/leggo/site/phpunit.xml
      - ../site/phpstan.neon:/var/www/leggo/site/phpstan.neon
      - ../manager/public_html/:/var/www/leggo/manager/public_html/
      - ../manager/app/:/var/www/leggo/manager/app/
      - ../manager/cgi-bin/:/var/www/leggo/manager/cgi-bin/
      - ../manager/tests/:/var/www/leggo/manager/tests/
      - ../manager/phpunit.xml:/var/www/leggo/manager/phpunit.xml
      - ../manager/phpstan.neon:/var/www/leggo/manager/phpstan.neon
      - ../migrations/:/var/www/leggo/migrations/
    ports:
      - "80:80"
    networks:
      leggo:
        ipv4_address: 172.29.0.3
  # Data Layer
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --sql_mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ../_data/mysql-data/:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    expose:
      - "3306"
    networks:
      leggo:
        ipv4_address: 172.29.0.2

  # Cache Layer
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy volatile-lru
      --save 60 1000
      --appendonly yes
    volumes:
      - ../_data/redis-data/:/data
    ports:
      - "127.0.0.1:6379:6379"
    expose:
      - "6379"
    networks:
      leggo:
        ipv4_address: 172.29.0.4
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  leggo:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
